[variables]
MAVEN_OPTS = "-Xmx256m -XX:+UseG1GC"

[phases.build]
cmds = [
    "mvn clean package -DskipTests -Dmaven.javadoc.skip=true"
]

[phases.start]
cmd = "java $JAVA_OPTS -jar target/chess-api-0.0.1-SNAPSHOT.jar"